<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Sippeers extends Model
{
    use HasFactory;
    protected $table = 'sippeers';
    protected $fillable = [
        'id_parent',
        'id_member',
        'name',
        'ipaddr',
        'port',
        'regseconds',
        'defaultuser',
        'fullcontact',
        'regserver',
        'useragent',
        'lastms',
        'host',
        'type',
        'context',
        'permit',
        'deny',
        'secret',
        'md5secret',
        'remotesecret',
        'transport',
        'dtmfmode',
        'directmedia',
        'nat',
        'callgroup',
        'pickupgroup',
        'language',
        'disallow',
        'allow',
        'insecure',
        'trustrpid',
        'progressinband',
        'promiscredir',
        'useclientcode',
        'accountcode',
        'setvar',
        'callerid',
        'amaflags',
        'callcounter',
        'busylevel',
        'allowoverlap',
        'allowsubscribe',
        'videosupport',
        'maxcallbitrate',
        'rfc2833compensate',
        'mailbox',
        'session-timers',
        'session-expires',
        'session-minse',
        'session-refresher',
        't38pt_usertpsource',
        'regexten',
        'fromdomain',
        'fromuser',
        'qualify',
        'defaultip',
        'rtptimeout',
        'rtpholdtimeout',
        'sendrpid',
        'outboundproxy',
        'callbackextension',
        'timert1',
        'timerb',
        'qualifyfreq',
        'constantssrc',
        'contactpermit',
        'contactdeny',
        'usereqphone',
        'textsupport',
        'faxdetect',
        'buggymwi',
        'auth',
        'fullname',
        'trunkname',
        'cid_number',
        'callingpres',
        'mohinterpret',
        'mohsuggest',
        'parkinglot',
        'hasvoicemail',
        'subscribemwi',
        'vmexten',
        'autoframing',
        'rtpkeepalive',
        'call-limit',
        'g726nonstandard',
        'ignoresdpversion',
        'allowtransfer',
        'dynamic',
        'path',
        'created_by',
        'supportpath'
    ];

    public function member_name() {
        return $this->hasOne('App\Models\Dialer_member', 'id', 'id_member');
    }
}
